/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SociedadesRouteImport } from './routes/sociedades'
import { Route as RetosRouteImport } from './routes/retos'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s.$id'

const SociedadesRoute = SociedadesRouteImport.update({
  id: '/sociedades',
  path: '/sociedades',
  getParentRoute: () => rootRouteImport,
} as any)
const RetosRoute = RetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/ranking': typeof RankingRoute
  '/reportar': typeof ReportarRoute
  '/retos': typeof RetosRoute
  '/sociedades': typeof SociedadesRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/ranking': typeof RankingRoute
  '/reportar': typeof ReportarRoute
  '/retos': typeof RetosRoute
  '/sociedades': typeof SociedadesRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/ranking': typeof RankingRoute
  '/reportar': typeof ReportarRoute
  '/retos': typeof RetosRoute
  '/sociedades': typeof SociedadesRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/lista'
    | '/login'
    | '/mapa'
    | '/onboarding'
    | '/ranking'
    | '/reportar'
    | '/retos'
    | '/sociedades'
    | '/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/lista'
    | '/login'
    | '/mapa'
    | '/onboarding'
    | '/ranking'
    | '/reportar'
    | '/retos'
    | '/sociedades'
    | '/s/$id'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/lista'
    | '/login'
    | '/mapa'
    | '/onboarding'
    | '/ranking'
    | '/reportar'
    | '/retos'
    | '/sociedades'
    | '/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  OnboardingRoute: typeof OnboardingRoute
  RankingRoute: typeof RankingRoute
  ReportarRoute: typeof ReportarRoute
  RetosRoute: typeof RetosRoute
  SociedadesRoute: typeof SociedadesRoute
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sociedades': {
      id: '/sociedades'
      path: '/sociedades'
      fullPath: '/sociedades'
      preLoaderRoute: typeof SociedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retos': {
      id: '/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof RetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  OnboardingRoute: OnboardingRoute,
  RankingRoute: RankingRoute,
  ReportarRoute: ReportarRoute,
  RetosRoute: RetosRoute,
  SociedadesRoute: SociedadesRoute,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
