/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RetosRouteImport } from './routes/retos'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SociedadesIndexRouteImport } from './routes/sociedades.index'
import { Route as EspeciesIndexRouteImport } from './routes/especies.index'
import { Route as SociedadesIdRouteImport } from './routes/sociedades.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as EspeciesIdRouteImport } from './routes/especies.$id'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RetosRoute = RetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SociedadesIndexRoute = SociedadesIndexRouteImport.update({
  id: '/sociedades/',
  path: '/sociedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspeciesIndexRoute = EspeciesIndexRouteImport.update({
  id: '/especies/',
  path: '/especies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SociedadesIdRoute = SociedadesIdRouteImport.update({
  id: '/sociedades/$id',
  path: '/sociedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EspeciesIdRoute = EspeciesIdRouteImport.update({
  id: '/especies/$id',
  path: '/especies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/ranking': typeof RankingRoute
  '/reportar': typeof ReportarRoute
  '/retos': typeof RetosRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/especies/$id': typeof EspeciesIdRoute
  '/s/$id': typeof SIdRoute
  '/sociedades/$id': typeof SociedadesIdRoute
  '/especies/': typeof EspeciesIndexRoute
  '/sociedades/': typeof SociedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/ranking': typeof RankingRoute
  '/reportar': typeof ReportarRoute
  '/retos': typeof RetosRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/especies/$id': typeof EspeciesIdRoute
  '/s/$id': typeof SIdRoute
  '/sociedades/$id': typeof SociedadesIdRoute
  '/especies': typeof EspeciesIndexRoute
  '/sociedades': typeof SociedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/ranking': typeof RankingRoute
  '/reportar': typeof ReportarRoute
  '/retos': typeof RetosRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/especies/$id': typeof EspeciesIdRoute
  '/s/$id': typeof SIdRoute
  '/sociedades/$id': typeof SociedadesIdRoute
  '/especies/': typeof EspeciesIndexRoute
  '/sociedades/': typeof SociedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/lista'
    | '/login'
    | '/mapa'
    | '/onboarding'
    | '/privacy'
    | '/ranking'
    | '/reportar'
    | '/retos'
    | '/support'
    | '/terms'
    | '/admin/reportes'
    | '/especies/$id'
    | '/s/$id'
    | '/sociedades/$id'
    | '/especies/'
    | '/sociedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/lista'
    | '/login'
    | '/mapa'
    | '/onboarding'
    | '/privacy'
    | '/ranking'
    | '/reportar'
    | '/retos'
    | '/support'
    | '/terms'
    | '/admin/reportes'
    | '/especies/$id'
    | '/s/$id'
    | '/sociedades/$id'
    | '/especies'
    | '/sociedades'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/lista'
    | '/login'
    | '/mapa'
    | '/onboarding'
    | '/privacy'
    | '/ranking'
    | '/reportar'
    | '/retos'
    | '/support'
    | '/terms'
    | '/admin/reportes'
    | '/especies/$id'
    | '/s/$id'
    | '/sociedades/$id'
    | '/especies/'
    | '/sociedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingRoute: typeof RankingRoute
  ReportarRoute: typeof ReportarRoute
  RetosRoute: typeof RetosRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AdminReportesRoute: typeof AdminReportesRoute
  EspeciesIdRoute: typeof EspeciesIdRoute
  SIdRoute: typeof SIdRoute
  SociedadesIdRoute: typeof SociedadesIdRoute
  EspeciesIndexRoute: typeof EspeciesIndexRoute
  SociedadesIndexRoute: typeof SociedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retos': {
      id: '/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof RetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sociedades/': {
      id: '/sociedades/'
      path: '/sociedades'
      fullPath: '/sociedades/'
      preLoaderRoute: typeof SociedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especies/': {
      id: '/especies/'
      path: '/especies'
      fullPath: '/especies/'
      preLoaderRoute: typeof EspeciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sociedades/$id': {
      id: '/sociedades/$id'
      path: '/sociedades/$id'
      fullPath: '/sociedades/$id'
      preLoaderRoute: typeof SociedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especies/$id': {
      id: '/especies/$id'
      path: '/especies/$id'
      fullPath: '/especies/$id'
      preLoaderRoute: typeof EspeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RankingRoute: RankingRoute,
  ReportarRoute: ReportarRoute,
  RetosRoute: RetosRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AdminReportesRoute: AdminReportesRoute,
  EspeciesIdRoute: EspeciesIdRoute,
  SIdRoute: SIdRoute,
  SociedadesIdRoute: SociedadesIdRoute,
  EspeciesIndexRoute: EspeciesIndexRoute,
  SociedadesIndexRoute: SociedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
